### ISSUE TITLE
go runtime panic

### ISSUE THREAD

**Issue by mec07** [unidoc/unioffice#292]
## Description
Came across a runtime panic when trying to make a presentation using a template.

## Expected Behavior
No runtime panic!

## Actual Behavior
The following code:
```
	ppt, err := presentation.OpenTemplate("template.pptx")
	for i, layout := range ppt.SlideLayouts() {
		fmt.Println(i, " LL ", layout.Name(), "/", layout.Type())
	}

	// remove any existing slides
	for _, s := range ppt.Slides() {
		ppt.RemoveSlide(s)
	}
	l, err := ppt.GetLayoutByName("Title Slide")
	if err != nil {
		log.Fatalf("error retrieving layout: %s", err)
	}
	sld, err := ppt.AddDefaultSlideWithLayout(l)
	if err != nil {
		log.Fatalf("error adding slide: %s", err)
	}
```
lead to the following (I ran the code from a test):
```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 19 [running]:
testing.tRunner.func1(0xc0001b0100)
	/usr/local/Cellar/go/1.12.4/libexec/src/testing/testing.go:830 +0x392
panic(0x181d760, 0x1ed2f70)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522 +0x1b5
github.com/unidoc/unioffice/presentation.(*Presentation).AddSlideWithLayout(0xc0001c6000, 0xc0000bcb40, 0xc000eede48, 0x9, 0x49, 0x696c732f7470702f, 0x64696c732f736564)
	/Users/marc/pkg/mod/github.com/unidoc/unioffice@v1.1.0/presentation/presentation.go:327 +0xeaa
github.com/unidoc/unioffice/presentation.(*Presentation).AddDefaultSlideWithLayout(0xc0001c6000, 0xc0000bcb40, 0xb, 0xc0000bcb40, 0x0, 0x0, 0xc000260100)
	/Users/marc/pkg/mod/github.com/unidoc/unioffice@v1.1.0/presentation/presentation.go:357 +0x4d
github.com/shellagilehub/coc-activity-export-api/internal/ppt.addSlideLayoutByName(0xc0001c6000, 0x18d3e53, 0xb, 0xc0001c6000, 0x0, 0x0, 0x105f5f0, 0xc0001ba730)
```
Unfortunately I can't put the template in this as it's not my property, but I have made a fix for this, with a working example test that triggers the runtime panic: https://github.com/unidoc/unioffice/pull/291

**Comment by mec07** [comment]
This was fixed by #291
